### ISSUE TITLE
Meet with strange logs when running rnazWindow.pl and RNAz

### ISSUE THREAD

**Issue by Jiayu-Dong** [ViennaRNA/RNAz#11]
Hi!

When I was running ranzWindow.pl on my MAF file, there is some strange output like these:

substr outside of string at /home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 472, <$fh> line 6743253.
Use of uninitialized value $t in string ne at /home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 472, <$fh> line 6743253.
substr outside of string at /home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 472, <$fh> line 6743253.
Use of uninitialized value $t in string ne at /home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 472, <$fh> line 6743253.
........

When I was running RNAz on my MAF file, there is some strange output like these:

Use of uninitialized value $rnaz[39] in scalar chomp at /home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 927, <$fh> line 568282.
Use of uninitialized value $rnaz[39] in substr at home/biosoft/RNA_Structure_MSA/RNAz-2.1/share/RNAz/perl/RNAz.pm line 930, <$fh> line 568282.
........

I was wondering why did this occur, would it affect the final results?

Thank you in advance for your help!

**Comment by svenderheld** [comment]
Dear Jiayu-Dong,

Would it be possible to receive a minimal input example that causes the above-mentioned issues? 
Otherwise, it's really hard to answer your question.

(Sorry for the late reply but I've been off for a couple of months.)
