### ISSUE TITLE
Patches needed for installation

### ISSUE THREAD

**Issue by Bernhard10** [ViennaRNA/RNAz#7]
The following fixes are necessary (at least with the current version 3.18 of libsvm)
- in the file rnaz/svm_helper.c remove everything from "struct svm_model{" until "};"
- in the file rnaz/svm_helper.h add the line 
  "#define svm_destroy_model(A) svm_free_model_content((A))" at the top of the file.
- in the file rnaz/strand.c insert a "&" before z_score_type in the following 2 lines:
  singleZ=mfe_zscore(woGapsSeq,singleMFE,z_score_type,0,warningString_strand);      singleZ_reverse=mfe_zscore(woGapsSeq_reverse,singleMFE_reverse,z_score_type,0,warningString_strand);

As described in dist.info, you need to download and unpack the svm library and to change libsvm-2.89 to libsvm-3.18 in Makefile.am and in rnaz/Makefile.am

With these patches, at least the source code compiles and there is no obviouse bug in the program. I hope they do not introduce a logical error into the program. ;)

**Comment by RaumZeit** [comment]
`libsvm-2.23` together with all necessary patches is already included in the source tree now...
