### ISSUE TITLE
Lib svm.h not found.

### ISSUE THREAD

**Issue by ivo-pontes** [ViennaRNA/RNAz#9]
Hello, recently I've tried to install the RNAz but I could not install it.

I used those commands:

sudo apt install med-bio

cd rnaz-master/

sh autogen.sh 
./configure
make

My output is:
...
-MT RNAz.o -MD -MP -MF .deps/RNAz.Tpo -c -o RNAz.o RNAz.c
RNAz.c:27:17: fatal error: svm.h: Arquivo ou diretório não encontrado
compilation terminated.
Makefile:376: recipe for target 'RNAz.o' failed
make[2]: *** [RNAz.o] Error 1
make[2]: Leaving directory '/home/ivo-ncrna/Downloads/rnaz-master/rnaz'
Makefile:412: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ivo-ncrna/Downloads/rnaz-master'
Makefile:332: recipe for target 'all' failed
make: *** [all] Error 2

It basically means that I have no svm.h(library) installed. How do I solve this problem. I tried the older versions too.

Can someone at least say how can I install the older versions?
Thanks in advance.

**Comment by RaumZeit** [comment]
Resolved in latest version 2.1.1
